# Site settings
title: "electronicnomad's Home"
description: "전자유목민의 집구석"
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "Kwanghoon Jhin"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics: UA-113185952-1
disqus_shortname:
