# Site settings
title: "electronicnomad's Home"
description: "전자유목민의 집구석"
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "an electronic nomad"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
##google_analytics: UA-113185952-1
##google_tracking_id: UA-113185952-1
google_analytics: G-GMF02VSY8W
google_tracking_id: G-GMF02VSY8W
disqus_shortname:

#port: 4001

plugins:
- jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
